configure: Fix zlib detection
The configure script failed to detect zlib. Even when the required
libraries and development files are installed, the configure outputted
the following:

> checking for zlib package... no

This issue occurs when using gcc-14, which treats some warnings as
errors. Below is the relevant part of the config.log preceding this
patch:

> configure:5472: checking for zlib package
> configure:5500: gcc -E  conftest.c
> configure:5500: $? = 0
> configure:5537: gcc -o conftest -g -O2   conftest.c -lz -lcrypt  >&5
> conftest.c: In function 'main':
> conftest.c:90:1: error: implicit declaration of function 'inflate' [-Wimplicit-function-declaration]
>    90 | inflate()
>       | ^~~~~~~
> configure:5537: $? = 1